### PR TITLE
ENH: drop thin wrappers

### PR DESCRIPTION
**Pull request by Jorge-C**
This looks cleaner to me than keeping the wrappers so far.

### CODE REVIEW

**Comment by wasade** [comment]
will this actually work? won't those methods complain with `**kwargs`?

**Comment by Jorge-C** [comment]
Is this your concern or something else I'm missing?

```
In [14]: def f(**kwargs):
   ....:     return g(**kwargs)
   ....: 

In [15]: def g():
   ....:     return 'yes!'
   ....: 

In [16]: f()
Out[16]: 'yes!'
```

**Comment by wasade** [comment]
Close, this:

``` python
> def foo():
   ...:     pass
   ...:

14:50:04 (mcdonadt@rl1-1-222-192-dhcp):/Users/mcdonadt/not_backed_up/ag_r1-15
> d = {'x': 5}

14:50:08 (mcdonadt@rl1-1-222-192-dhcp):/Users/mcdonadt/not_backed_up/ag_r1-15
> foo(**d)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-f5b67fd1ef0f> in <module>()
----> 1 foo(**d)

TypeError: foo() takes no arguments (1 given)
```

**Comment by Jorge-C** [comment]
Sure, but if the user is providing args that are being ignored if we keep the wrappers, I'd argue that it's better to fail rather than ignore them silently, following Python's zen :)

**Comment by wasade** [comment]
I thought the python zen was to just work regardless of if its a good idea
:) but ya, complaining loudly is a good practice.

**Pull request merged**
